//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucifer.Ics.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucifer.Ics.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current production item.
        /// </summary>
        public static string AllProductionItemsView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllProductionItemsView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string AllProductionItemsView_Header_ItemNames {
            get {
                return ResourceManager.GetString("AllProductionItemsView_Header_ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllProductionItemsView_Header_Name {
            get {
                return ResourceManager.GetString("AllProductionItemsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.-Unit.
        /// </summary>
        public static string AllProductionItemsView_Header_RecipeUnit {
            get {
                return ResourceManager.GetString("AllProductionItemsView_Header_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new production item.
        /// </summary>
        public static string AllProductionItemsView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllProductionItemsView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current production item.
        /// </summary>
        public static string AllProductionItemsView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllProductionItemsView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following production items:
        ///.
        /// </summary>
        public static string AllProductionItemsView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllProductionItemsView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove production items.
        /// </summary>
        public static string AllProductionItemsView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllProductionItemsView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current purchase family.
        /// </summary>
        public static string AllPurchaseFamiliesView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseFamiliesView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllPurchaseFamiliesView_Header_Name {
            get {
                return ResourceManager.GetString("AllPurchaseFamiliesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new purchase family.
        /// </summary>
        public static string AllPurchaseFamiliesView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseFamiliesView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current purchase family.
        /// </summary>
        public static string AllPurchaseFamiliesView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseFamiliesView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following purchase families:
        ///.
        /// </summary>
        public static string AllPurchaseFamiliesView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllPurchaseFamiliesView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove purchase families.
        /// </summary>
        public static string AllPurchaseFamiliesView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllPurchaseFamiliesView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current purchase item.
        /// </summary>
        public static string AllPurchaseItemsView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string AllPurchaseItemsView_Header_Family {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_Header_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllPurchaseItemsView_Header_Name {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.-Unit.
        /// </summary>
        public static string AllPurchaseItemsView_Header_PurchaseUnit {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_Header_PurchaseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.-Unit.
        /// </summary>
        public static string AllPurchaseItemsView_Header_RecipeUnit {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_Header_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new purchase item.
        /// </summary>
        public static string AllPurchaseItemsView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current purchase item.
        /// </summary>
        public static string AllPurchaseItemsView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following purchase items:
        ///.
        /// </summary>
        public static string AllPurchaseItemsView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove purchase items.
        /// </summary>
        public static string AllPurchaseItemsView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllPurchaseItemsView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current recipe.
        /// </summary>
        public static string AllRecipesView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllRecipesView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string AllRecipesView_Header_ItemNames {
            get {
                return ResourceManager.GetString("AllRecipesView_Header_ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu.
        /// </summary>
        public static string AllRecipesView_Header_Plu {
            get {
                return ResourceManager.GetString("AllRecipesView_Header_Plu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new recipe.
        /// </summary>
        public static string AllRecipesView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllRecipesView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current recipe.
        /// </summary>
        public static string AllRecipesView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllRecipesView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following recipes:
        ///.
        /// </summary>
        public static string AllRecipesView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllRecipesView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove recipes.
        /// </summary>
        public static string AllRecipesView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllRecipesView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current stock.
        /// </summary>
        public static string AllStocksView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllStocksView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string AllStocksView_Header_ItemNames {
            get {
                return ResourceManager.GetString("AllStocksView_Header_ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string AllStocksView_Header_MainStock {
            get {
                return ResourceManager.GetString("AllStocksView_Header_MainStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllStocksView_Header_Name {
            get {
                return ResourceManager.GetString("AllStocksView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new stock.
        /// </summary>
        public static string AllStocksView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllStocksView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current stock.
        /// </summary>
        public static string AllStocksView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllStocksView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following stocks:
        ///.
        /// </summary>
        public static string AllStocksView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllStocksView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove stocks.
        /// </summary>
        public static string AllStocksView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllStocksView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current unit.
        /// </summary>
        public static string AllUnitsView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitsView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        public static string AllUnitsView_Header_Contraction {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string AllUnitsView_Header_FactorToParent {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_FactorToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string AllUnitsView_Header_Parent {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        public static string AllUnitsView_Header_Purchasing {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciping.
        /// </summary>
        public static string AllUnitsView_Header_Reciping {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Reciping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AllUnitsView_Header_UnitType {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new unit.
        /// </summary>
        public static string AllUnitsView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitsView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current unit.
        /// </summary>
        public static string AllUnitsView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitsView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following units:
        ///.
        /// </summary>
        public static string AllUnitsView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllUnitsView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove units.
        /// </summary>
        public static string AllUnitsView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllUnitsView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current unit type.
        /// </summary>
        public static string AllUnitTypesView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitTypesView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUnitTypesView_Header_Name {
            get {
                return ResourceManager.GetString("AllUnitTypesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new unit type.
        /// </summary>
        public static string AllUnitTypesView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitTypesView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current unit type.
        /// </summary>
        public static string AllUnitTypesView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitTypesView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following unit types:
        ///.
        /// </summary>
        public static string AllUnitTypesView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllUnitTypesView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unit types.
        /// </summary>
        public static string AllUnitTypesView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllUnitTypesView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditProductionItemView_Name {
            get {
                return ResourceManager.GetString("EditProductionItemView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New production item&gt;.
        /// </summary>
        public static string EditProductionItemView_NewProductionItem {
            get {
                return ResourceManager.GetString("EditProductionItemView_NewProductionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production item {0}.
        /// </summary>
        public static string EditProductionItemView_ProductionItemIs {
            get {
                return ResourceManager.GetString("EditProductionItemView_ProductionItemIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recipe unit:.
        /// </summary>
        public static string EditProductionItemView_RecipeUnit {
            get {
                return ResourceManager.GetString("EditProductionItemView_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit production item.
        /// </summary>
        public static string EditProductionItemView_TitleEdit {
            get {
                return ResourceManager.GetString("EditProductionItemView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new production item.
        /// </summary>
        public static string EditProductionItemView_TitleNew {
            get {
                return ResourceManager.GetString("EditProductionItemView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditPurchaseFamilyView_Name {
            get {
                return ResourceManager.GetString("EditPurchaseFamilyView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New purchase family&gt;.
        /// </summary>
        public static string EditPurchaseFamilyView_NewPurchaseFamily {
            get {
                return ResourceManager.GetString("EditPurchaseFamilyView_NewPurchaseFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase family {0}.
        /// </summary>
        public static string EditPurchaseFamilyView_PurchaseFamilyIs {
            get {
                return ResourceManager.GetString("EditPurchaseFamilyView_PurchaseFamilyIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit purchase family.
        /// </summary>
        public static string EditPurchaseFamilyView_TitleEdit {
            get {
                return ResourceManager.GetString("EditPurchaseFamilyView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new purchase family....
        /// </summary>
        public static string EditPurchaseFamilyView_TitleNew {
            get {
                return ResourceManager.GetString("EditPurchaseFamilyView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Family:.
        /// </summary>
        public static string EditPurchaseItemView_Family {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditPurchaseItemView_Name {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New purchase item&gt;.
        /// </summary>
        public static string EditPurchaseItemView_NewPurchaseItem {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_NewPurchaseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase item {0}.
        /// </summary>
        public static string EditPurchaseItemView_PurchaseItemIs {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_PurchaseItemIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Purchase unit:.
        /// </summary>
        public static string EditPurchaseItemView_PurchaseUnit {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_PurchaseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recipe unit:.
        /// </summary>
        public static string EditPurchaseItemView_RecipeUnit {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit purchase item.
        /// </summary>
        public static string EditPurchaseItemView_TitleEdit {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new purchase item....
        /// </summary>
        public static string EditPurchaseItemView_TitleNew {
            get {
                return ResourceManager.GetString("EditPurchaseItemView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New recipe&gt;.
        /// </summary>
        public static string EditRecipeView_NewRecipe {
            get {
                return ResourceManager.GetString("EditRecipeView_NewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plu:.
        /// </summary>
        public static string EditRecipeView_Plu {
            get {
                return ResourceManager.GetString("EditRecipeView_Plu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe {0}.
        /// </summary>
        public static string EditRecipeView_RecipeIs {
            get {
                return ResourceManager.GetString("EditRecipeView_RecipeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit recipe.
        /// </summary>
        public static string EditRecipeView_TitleEdit {
            get {
                return ResourceManager.GetString("EditRecipeView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new recipe.
        /// </summary>
        public static string EditRecipeView_TitleNew {
            get {
                return ResourceManager.GetString("EditRecipeView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Main stock.
        /// </summary>
        public static string EditStockView_MainStock {
            get {
                return ResourceManager.GetString("EditStockView_MainStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditStockView_Name {
            get {
                return ResourceManager.GetString("EditStockView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New stock&gt;.
        /// </summary>
        public static string EditStockView_NewStock {
            get {
                return ResourceManager.GetString("EditStockView_NewStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock {0}.
        /// </summary>
        public static string EditStockView_PurchaseStockIs {
            get {
                return ResourceManager.GetString("EditStockView_PurchaseStockIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit stock.
        /// </summary>
        public static string EditStockView_TitleEdit {
            get {
                return ResourceManager.GetString("EditStockView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new stock.
        /// </summary>
        public static string EditStockView_TitleNew {
            get {
                return ResourceManager.GetString("EditStockView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string EditUnitTypeView_Name {
            get {
                return ResourceManager.GetString("EditUnitTypeView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New unit type&gt;.
        /// </summary>
        public static string EditUnitTypeView_NewUnitType {
            get {
                return ResourceManager.GetString("EditUnitTypeView_NewUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit unit type.
        /// </summary>
        public static string EditUnitTypeView_TitleEdit {
            get {
                return ResourceManager.GetString("EditUnitTypeView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit type....
        /// </summary>
        public static string EditUnitTypeView_TitleNew {
            get {
                return ResourceManager.GetString("EditUnitTypeView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type {0}.
        /// </summary>
        public static string EditUnitTypeView_UnitTypeIs {
            get {
                return ResourceManager.GetString("EditUnitTypeView_UnitTypeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Contraction:.
        /// </summary>
        public static string EditUnitView_Contraction {
            get {
                return ResourceManager.GetString("EditUnitView_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Factor to parent:.
        /// </summary>
        public static string EditUnitView_FactorToParent {
            get {
                return ResourceManager.GetString("EditUnitView_FactorToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditUnitView_Name {
            get {
                return ResourceManager.GetString("EditUnitView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New unit&gt;.
        /// </summary>
        public static string EditUnitView_NewUnit {
            get {
                return ResourceManager.GetString("EditUnitView_NewUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Parent:.
        /// </summary>
        public static string EditUnitView_Parent {
            get {
                return ResourceManager.GetString("EditUnitView_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for purchasing.
        /// </summary>
        public static string EditUnitView_Purchasing {
            get {
                return ResourceManager.GetString("EditUnitView_Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for reciping.
        /// </summary>
        public static string EditUnitView_Reciping {
            get {
                return ResourceManager.GetString("EditUnitView_Reciping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit unit.
        /// </summary>
        public static string EditUnitView_TitleEdit {
            get {
                return ResourceManager.GetString("EditUnitView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit....
        /// </summary>
        public static string EditUnitView_TitleNew {
            get {
                return ResourceManager.GetString("EditUnitView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit {0}.
        /// </summary>
        public static string EditUnitView_UnitIs {
            get {
                return ResourceManager.GetString("EditUnitView_UnitIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit _type:.
        /// </summary>
        public static string EditUnitView_UnitType {
            get {
                return ResourceManager.GetString("EditUnitView_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Control.
        /// </summary>
        public static string IcsModuleTitle {
            get {
                return ResourceManager.GetString("IcsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your inventories, stocks, ....
        /// </summary>
        public static string IcsModuleTooltip {
            get {
                return ResourceManager.GetString("IcsModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of production item is missing.
        /// </summary>
        public static string ProductionItemModel_Name_missing {
            get {
                return ResourceManager.GetString("ProductionItemModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe unit of production item is missing.
        /// </summary>
        public static string ProductionItemModel_RecipeUnit_is_missing {
            get {
                return ResourceManager.GetString("ProductionItemModel_RecipeUnit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production items.
        /// </summary>
        public static string ProductionItemsModule {
            get {
                return ResourceManager.GetString("ProductionItemsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage production items.
        /// </summary>
        public static string ProductionItemsTooltip {
            get {
                return ResourceManager.GetString("ProductionItemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase families.
        /// </summary>
        public static string PurchaseFamiliesModule {
            get {
                return ResourceManager.GetString("PurchaseFamiliesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase families to group purchase items.
        /// </summary>
        public static string PurchaseFamiliesTooltip {
            get {
                return ResourceManager.GetString("PurchaseFamiliesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of purchase family is missing.
        /// </summary>
        public static string PurchaseFamilyModel_Name_missing {
            get {
                return ResourceManager.GetString("PurchaseFamilyModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the purchase item is missing.
        /// </summary>
        public static string PurchaseItemModel_Name_missing {
            get {
                return ResourceManager.GetString("PurchaseItemModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family of the purchase item is missing.
        /// </summary>
        public static string PurchaseItemModel_PurchaseFamily_is_missing {
            get {
                return ResourceManager.GetString("PurchaseItemModel_PurchaseFamily_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase unit of the purchase item is missing.
        /// </summary>
        public static string PurchaseItemModel_PurchaseUnit_is_missing {
            get {
                return ResourceManager.GetString("PurchaseItemModel_PurchaseUnit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe unit of the purchase item is missing.
        /// </summary>
        public static string PurchaseItemModel_RecipeUnit_is_missing {
            get {
                return ResourceManager.GetString("PurchaseItemModel_RecipeUnit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase items.
        /// </summary>
        public static string PurchaseItemsModule {
            get {
                return ResourceManager.GetString("PurchaseItemsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage purchase items.
        /// </summary>
        public static string PurchaseItemsTooltip {
            get {
                return ResourceManager.GetString("PurchaseItemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU of recipe is missing.
        /// </summary>
        public static string RecipeModel_Plu_missing {
            get {
                return ResourceManager.GetString("RecipeModel_Plu_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipesModule {
            get {
                return ResourceManager.GetString("RecipesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes and their ingredients.
        /// </summary>
        public static string RecipesTooltip {
            get {
                return ResourceManager.GetString("RecipesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the stock is missing.
        /// </summary>
        public static string StockModel_Name_missing {
            get {
                return ResourceManager.GetString("StockModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string StocksModule {
            get {
                return ResourceManager.GetString("StocksModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage stocks.
        /// </summary>
        public static string StocksTooltip {
            get {
                return ResourceManager.GetString("StocksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction of the unit is missing.
        /// </summary>
        public static string UnitModel_Contraction_missing {
            get {
                return ResourceManager.GetString("UnitModel_Contraction_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor to parent is invalid.
        /// </summary>
        public static string UnitModel_FactorToParent_invalid {
            get {
                return ResourceManager.GetString("UnitModel_FactorToParent_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor to parent is missing.
        /// </summary>
        public static string UnitModel_FactorToParent_missing {
            get {
                return ResourceManager.GetString("UnitModel_FactorToParent_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent&apos;s type is invalid.
        /// </summary>
        public static string UnitModel_InvalidParentType {
            get {
                return ResourceManager.GetString("UnitModel_InvalidParentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the unit is missing.
        /// </summary>
        public static string UnitModel_Name_missing {
            get {
                return ResourceManager.GetString("UnitModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursion in parent of this unit detected.
        /// </summary>
        public static string UnitModel_Parent_recursion_detected {
            get {
                return ResourceManager.GetString("UnitModel_Parent_recursion_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type of the unit is missing.
        /// </summary>
        public static string UnitModel_UnitType_missing {
            get {
                return ResourceManager.GetString("UnitModel_UnitType_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitsModule {
            get {
                return ResourceManager.GetString("UnitsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage measurement units.
        /// </summary>
        public static string UnitsTooltip {
            get {
                return ResourceManager.GetString("UnitsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the unit type is missing.
        /// </summary>
        public static string UnitTypeModel_Name_missing {
            get {
                return ResourceManager.GetString("UnitTypeModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit types.
        /// </summary>
        public static string UnitTypesModule {
            get {
                return ResourceManager.GetString("UnitTypesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage unit types for grouping units.
        /// </summary>
        public static string UnitTypesTooltip {
            get {
                return ResourceManager.GetString("UnitTypesTooltip", resourceCulture);
            }
        }
    }
}
