//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucifer.Ics.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucifer.Ics.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current unit.
        /// </summary>
        public static string AllUnitsView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitsView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        public static string AllUnitsView_Header_Contraction {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string AllUnitsView_Header_FactorToParent {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_FactorToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string AllUnitsView_Header_Parent {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        public static string AllUnitsView_Header_Purchasing {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciping.
        /// </summary>
        public static string AllUnitsView_Header_Reciping {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_Reciping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AllUnitsView_Header_UnitType {
            get {
                return ResourceManager.GetString("AllUnitsView_Header_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new unit.
        /// </summary>
        public static string AllUnitsView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitsView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current unit.
        /// </summary>
        public static string AllUnitsView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitsView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current unit type.
        /// </summary>
        public static string AllUnitTypesView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitTypesView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUnitTypesView_Header_Name {
            get {
                return ResourceManager.GetString("AllUnitTypesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a new unit type.
        /// </summary>
        public static string AllUnitTypesView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitTypesView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current unit type.
        /// </summary>
        public static string AllUnitTypesView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllUnitTypesView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string EditUnitTypeView_Name {
            get {
                return ResourceManager.GetString("EditUnitTypeView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New unit type&gt;.
        /// </summary>
        public static string EditUnitTypeView_NewUnitType {
            get {
                return ResourceManager.GetString("EditUnitTypeView_NewUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit unit type.
        /// </summary>
        public static string EditUnitTypeView_TitleEdit {
            get {
                return ResourceManager.GetString("EditUnitTypeView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit type....
        /// </summary>
        public static string EditUnitTypeView_TitleNew {
            get {
                return ResourceManager.GetString("EditUnitTypeView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Control.
        /// </summary>
        public static string IcsModuleTitle {
            get {
                return ResourceManager.GetString("IcsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your inventories, stocks, ....
        /// </summary>
        public static string IcsModuleTooltip {
            get {
                return ResourceManager.GetString("IcsModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitsModule {
            get {
                return ResourceManager.GetString("UnitsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage measurement units.
        /// </summary>
        public static string UnitsTooltip {
            get {
                return ResourceManager.GetString("UnitsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit types.
        /// </summary>
        public static string UnitTypesModule {
            get {
                return ResourceManager.GetString("UnitTypesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage unit types for grouping units.
        /// </summary>
        public static string UnitTypesTooltip {
            get {
                return ResourceManager.GetString("UnitTypesTooltip", resourceCulture);
            }
        }
    }
}
