//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportViewer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out Crystal Reports.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Reports_groupInformation {
            get {
                return ResourceManager.GetString("Reports_groupInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Reports_groupSelection {
            get {
                return ResourceManager.GetString("Reports_groupSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Reports_lbAuthor {
            get {
                return ResourceManager.GetString("Reports_lbAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        public static string Reports_lbComments {
            get {
                return ResourceManager.GetString("Reports_lbComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields:.
        /// </summary>
        public static string Reports_lbFields {
            get {
                return ResourceManager.GetString("Reports_lbFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name:.
        /// </summary>
        public static string Reports_lbFileName {
            get {
                return ResourceManager.GetString("Reports_lbFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords:.
        /// </summary>
        public static string Reports_lbKeywords {
            get {
                return ResourceManager.GetString("Reports_lbKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report name:.
        /// </summary>
        public static string Reports_lbReportName {
            get {
                return ResourceManager.GetString("Reports_lbReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report:.
        /// </summary>
        public static string Reports_lbSelectReport {
            get {
                return ResourceManager.GetString("Reports_lbSelectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string Reports_lbSubject {
            get {
                return ResourceManager.GetString("Reports_lbSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Reports_lbTitle {
            get {
                return ResourceManager.GetString("Reports_lbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded.
        /// </summary>
        public static string Reports_tabEmbedded {
            get {
                return ResourceManager.GetString("Reports_tabEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string Reports_tabExternal {
            get {
                return ResourceManager.GetString("Reports_tabExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Reports_tabReport {
            get {
                return ResourceManager.GetString("Reports_tabReport", resourceCulture);
            }
        }
    }
}
