//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaOwl.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LastFmDataAccess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LastFmDataAccess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaOwl.Services.LastFmDataAccess", typeof(LastFmDataAccess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.lastfm.de/api/intro.
        /// </summary>
        internal static string ApiDescription {
            get {
                return ResourceManager.GetString("ApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ws.audioscrobbler.com/2.0/.
        /// </summary>
        internal static string BaseUri {
            get {
                return ResourceManager.GetString("BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.getinfo.
        /// </summary>
        internal static string MethodAlbumGetInfo {
            get {
                return ResourceManager.GetString("MethodAlbumGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.search.
        /// </summary>
        internal static string MethodAlbumSearch {
            get {
                return ResourceManager.GetString("MethodAlbumSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.getevents.
        /// </summary>
        internal static string MethodArtistGetEvents {
            get {
                return ResourceManager.GetString("MethodArtistGetEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.getinfo.
        /// </summary>
        internal static string MethodArtistGetInfo {
            get {
                return ResourceManager.GetString("MethodArtistGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.getsimilar.
        /// </summary>
        internal static string MethodArtistGetSimilar {
            get {
                return ResourceManager.GetString("MethodArtistGetSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.gettopalbums.
        /// </summary>
        internal static string MethodArtistGetTopAlbums {
            get {
                return ResourceManager.GetString("MethodArtistGetTopAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.gettoptags.
        /// </summary>
        internal static string MethodArtistGetTopTags {
            get {
                return ResourceManager.GetString("MethodArtistGetTopTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.gettoptracks.
        /// </summary>
        internal static string MethodArtistGetTopTracks {
            get {
                return ResourceManager.GetString("MethodArtistGetTopTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.search.
        /// </summary>
        internal static string MethodArtistSearch {
            get {
                return ResourceManager.GetString("MethodArtistSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.gettopalbums.
        /// </summary>
        internal static string MethodTagGetTopAlbums {
            get {
                return ResourceManager.GetString("MethodTagGetTopAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.gettopartists.
        /// </summary>
        internal static string MethodTagGetTopArtists {
            get {
                return ResourceManager.GetString("MethodTagGetTopArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.gettoptags.
        /// </summary>
        internal static string MethodTagGetTopTags {
            get {
                return ResourceManager.GetString("MethodTagGetTopTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.gettoptracks.
        /// </summary>
        internal static string MethodTagGetTopTracks {
            get {
                return ResourceManager.GetString("MethodTagGetTopTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.getweeklyartistchart.
        /// </summary>
        internal static string MethodTagGetWeeklyArtistChart {
            get {
                return ResourceManager.GetString("MethodTagGetWeeklyArtistChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.getinfo.
        /// </summary>
        internal static string MethodTrackGetInfo {
            get {
                return ResourceManager.GetString("MethodTrackGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.getsimilar.
        /// </summary>
        internal static string MethodTrackGetSimilar {
            get {
                return ResourceManager.GetString("MethodTrackGetSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.search.
        /// </summary>
        internal static string MethodTrackSearch {
            get {
                return ResourceManager.GetString("MethodTrackSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://a9.com/-/spec/opensearch/1.1/.
        /// </summary>
        internal static string NameSpaceOpenSearch {
            get {
                return ResourceManager.GetString("NameSpaceOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        internal static string ParamAlbum {
            get {
                return ResourceManager.GetString("ParamAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api_key.
        /// </summary>
        internal static string ParamApiKey {
            get {
                return ResourceManager.GetString("ParamApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        internal static string ParamArtist {
            get {
                return ResourceManager.GetString("ParamArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autocorrect.
        /// </summary>
        internal static string ParamAutocorrect {
            get {
                return ResourceManager.GetString("ParamAutocorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        internal static string ParamLimit {
            get {
                return ResourceManager.GetString("ParamLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mbid.
        /// </summary>
        internal static string ParamMBID {
            get {
                return ResourceManager.GetString("ParamMBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method.
        /// </summary>
        internal static string ParamMethod {
            get {
                return ResourceManager.GetString("ParamMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string ParamPage {
            get {
                return ResourceManager.GetString("ParamPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        internal static string ParamTag {
            get {
                return ResourceManager.GetString("ParamTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        internal static string ParamTrack {
            get {
                return ResourceManager.GetString("ParamTrack", resourceCulture);
            }
        }
    }
}
