//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucifer.Ums.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucifer.Ums.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current user role.
        /// </summary>
        public static string AllUserRolesView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllUserRolesView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUserRolesView_Header_Name {
            get {
                return ResourceManager.GetString("AllUserRolesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new user role.
        /// </summary>
        public static string AllUserRolesView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllUserRolesView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current user role.
        /// </summary>
        public static string AllUserRolesView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllUserRolesView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following user roles:
        ///.
        /// </summary>
        public static string AllUserRolesView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllUserRolesView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user roles....
        /// </summary>
        public static string AllUserRolesView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllUserRolesView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current user.
        /// </summary>
        public static string AllUsersView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllUsersView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUsersView_Header_Name {
            get {
                return ResourceManager.GetString("AllUsersView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new user.
        /// </summary>
        public static string AllUsersView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllUsersView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current user.
        /// </summary>
        public static string AllUsersView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllUsersView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following users:
        ///.
        /// </summary>
        public static string AllUsersView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllUsersView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove users....
        /// </summary>
        public static string AllUsersView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllUsersView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditUserRoleView_Name {
            get {
                return ResourceManager.GetString("EditUserRoleView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user role....
        /// </summary>
        public static string EditUserRoleView_NewUserRole {
            get {
                return ResourceManager.GetString("EditUserRoleView_NewUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user role.
        /// </summary>
        public static string EditUserRoleView_TitleEdit {
            get {
                return ResourceManager.GetString("EditUserRoleView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New user role&gt;.
        /// </summary>
        public static string EditUserRoleView_TitleNew {
            get {
                return ResourceManager.GetString("EditUserRoleView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditUserView_Name {
            get {
                return ResourceManager.GetString("EditUserView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user....
        /// </summary>
        public static string EditUserView_NewUser {
            get {
                return ResourceManager.GetString("EditUserView_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditUserView_TitleEdit {
            get {
                return ResourceManager.GetString("EditUserView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New user&gt;.
        /// </summary>
        public static string EditUserView_TitleNew {
            get {
                return ResourceManager.GetString("EditUserView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UmsModuleTitle {
            get {
                return ResourceManager.GetString("UmsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user and their rights.
        /// </summary>
        public static string UmsModuleTooltip {
            get {
                return ResourceManager.GetString("UmsModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of user is missing.
        /// </summary>
        public static string UserModel_Name_missing {
            get {
                return ResourceManager.GetString("UserModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of user role is missing.
        /// </summary>
        public static string UserRoleModel_Name_missing {
            get {
                return ResourceManager.GetString("UserRoleModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string UserRolesModule {
            get {
                return ResourceManager.GetString("UserRolesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage different user roles.
        /// </summary>
        public static string UserRolesTooltip {
            get {
                return ResourceManager.GetString("UserRolesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersModule {
            get {
                return ResourceManager.GetString("UsersModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string UsersTooltip {
            get {
                return ResourceManager.GetString("UsersTooltip", resourceCulture);
            }
        }
    }
}
