//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Godot.IcsEditor.Ui.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Godot.IcsEditor.Ui.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Button_Help {
            get {
                return ResourceManager.GetString("Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print.
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book _from.
        /// </summary>
        public static string Button_Stocks_BookFrom {
            get {
                return ResourceManager.GetString("Button_Stocks_BookFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Deposit.
        /// </summary>
        public static string Button_Stocks_Deposit {
            get {
                return ResourceManager.GetString("Button_Stocks_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Removal.
        /// </summary>
        public static string Button_Stocks_Removal {
            get {
                return ResourceManager.GetString("Button_Stocks_Removal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send _to.
        /// </summary>
        public static string Button_Stocks_SendTo {
            get {
                return ResourceManager.GetString("Button_Stocks_SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Main bearing.
        /// </summary>
        public static string Button_Stocks_ShowMainbearing {
            get {
                return ResourceManager.GetString("Button_Stocks_ShowMainbearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to book stock items..
        /// </summary>
        public static string Error_BookItems_CannotBook {
            get {
                return ResourceManager.GetString("Error_BookItems_CannotBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete production item..
        /// </summary>
        public static string Error_ProductionItems_CannotDelete {
            get {
                return ResourceManager.GetString("Error_ProductionItems_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save production item..
        /// </summary>
        public static string Error_ProductionItems_CannotSave {
            get {
                return ResourceManager.GetString("Error_ProductionItems_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete production family..
        /// </summary>
        public static string Error_PurchaseFamilies_CannotDelete {
            get {
                return ResourceManager.GetString("Error_PurchaseFamilies_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save production family..
        /// </summary>
        public static string Error_PurchaseFamilies_CannotSave {
            get {
                return ResourceManager.GetString("Error_PurchaseFamilies_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete purchase item..
        /// </summary>
        public static string Error_PurchaseItems_CannotDelete {
            get {
                return ResourceManager.GetString("Error_PurchaseItems_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save purchase item..
        /// </summary>
        public static string Error_PurchaseItems_CannotSave {
            get {
                return ResourceManager.GetString("Error_PurchaseItems_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete recipe..
        /// </summary>
        public static string Error_Recipes_CannotDelete {
            get {
                return ResourceManager.GetString("Error_Recipes_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save recipe..
        /// </summary>
        public static string Error_Recipes_CannotSave {
            get {
                return ResourceManager.GetString("Error_Recipes_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete stock..
        /// </summary>
        public static string Error_Stocks_CannotDelete {
            get {
                return ResourceManager.GetString("Error_Stocks_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save stock..
        /// </summary>
        public static string Error_Stocks_CannotSave {
            get {
                return ResourceManager.GetString("Error_Stocks_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete unit..
        /// </summary>
        public static string Error_Units_CannotDelete {
            get {
                return ResourceManager.GetString("Error_Units_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save unit..
        /// </summary>
        public static string Error_Units_CannotSave {
            get {
                return ResourceManager.GetString("Error_Units_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete unit type..
        /// </summary>
        public static string Error_UnitTypes_CannotDelete {
            get {
                return ResourceManager.GetString("Error_UnitTypes_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save unit type..
        /// </summary>
        public static string Error_UnitTypes_CannotSave {
            get {
                return ResourceManager.GetString("Error_UnitTypes_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string Model_EditProductionItem_Name_is_missing {
            get {
                return ResourceManager.GetString("Model_EditProductionItem_Name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe unit is missing.
        /// </summary>
        public static string Model_EditProductionItem_RecipeUnit_is_missing {
            get {
                return ResourceManager.GetString("Model_EditProductionItem_RecipeUnit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string Model_EditPurchaseFamily_Name_is_missing {
            get {
                return ResourceManager.GetString("Model_EditPurchaseFamily_Name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string Model_EditPurchaseItem_Name_is_missing {
            get {
                return ResourceManager.GetString("Model_EditPurchaseItem_Name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase family is missing.
        /// </summary>
        public static string Model_EditPurchaseItem_PurchaseFamily_is_missing {
            get {
                return ResourceManager.GetString("Model_EditPurchaseItem_PurchaseFamily_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase unit is missing.
        /// </summary>
        public static string Model_EditPurchaseItem_PurchaseUnit_is_missing {
            get {
                return ResourceManager.GetString("Model_EditPurchaseItem_PurchaseUnit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe unit is missing.
        /// </summary>
        public static string Model_EditPurchaseItem_RecipeUnit_is_missing {
            get {
                return ResourceManager.GetString("Model_EditPurchaseItem_RecipeUnit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production item is missing.
        /// </summary>
        public static string Model_EditRecipeItem_Production_is_missing {
            get {
                return ResourceManager.GetString("Model_EditRecipeItem_Production_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is invalid.
        /// </summary>
        public static string Model_EditRecipeItem_Quantity_is_invalid {
            get {
                return ResourceManager.GetString("Model_EditRecipeItem_Quantity_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server cannot be empty..
        /// </summary>
        public static string Model_EditSettings_DbServer_is_invalid {
            get {
                return ResourceManager.GetString("Model_EditSettings_DbServer_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database user cannot be empty..
        /// </summary>
        public static string Model_EditSettings_DbUser_is_empty {
            get {
                return ResourceManager.GetString("Model_EditSettings_DbUser_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid matrix path..
        /// </summary>
        public static string Model_EditSettings_MatrixPath_is_invalid {
            get {
                return ResourceManager.GetString("Model_EditSettings_MatrixPath_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string Model_EditStock_Name_is_missing {
            get {
                return ResourceManager.GetString("Model_EditStock_Name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a stock item.
        /// </summary>
        public static string Model_EditStock_StockItem_is_missing {
            get {
                return ResourceManager.GetString("Model_EditStock_StockItem_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a unit.
        /// </summary>
        public static string Model_EditStock_Unit_is_missing {
            get {
                return ResourceManager.GetString("Model_EditStock_Unit_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction is missing.
        /// </summary>
        public static string Model_EditUnit_Contraction_is_missing {
            get {
                return ResourceManager.GetString("Model_EditUnit_Contraction_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given factor to parent is invalid.
        /// </summary>
        public static string Model_EditUnit_FactorToParent_is_invalid {
            get {
                return ResourceManager.GetString("Model_EditUnit_FactorToParent_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No factor to parent given.
        /// </summary>
        public static string Model_EditUnit_FactorToParent_is_missing {
            get {
                return ResourceManager.GetString("Model_EditUnit_FactorToParent_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent (wrong unit type).
        /// </summary>
        public static string Model_EditUnit_InvalidParentType {
            get {
                return ResourceManager.GetString("Model_EditUnit_InvalidParentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string Model_EditUnit_Name_is_missing {
            get {
                return ResourceManager.GetString("Model_EditUnit_Name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursion in parent detected.
        /// </summary>
        public static string Model_EditUnit_Parent_recursion_detected {
            get {
                return ResourceManager.GetString("Model_EditUnit_Parent_recursion_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type is missing.
        /// </summary>
        public static string Model_EditUnit_UnitType_is_missing {
            get {
                return ResourceManager.GetString("Model_EditUnit_UnitType_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string Model_EditUnitType_Name_is_missing {
            get {
                return ResourceManager.GetString("Model_EditUnitType_Name_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination stock is missing.
        /// </summary>
        public static string Model_MoveBookStockItems_Destination_is_missing {
            get {
                return ResourceManager.GetString("Model_MoveBookStockItems_Destination_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to book.
        /// </summary>
        public static string Model_MoveBookStockItems_Nothing_to_Book {
            get {
                return ResourceManager.GetString("Model_MoveBookStockItems_Nothing_to_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source stock is missing.
        /// </summary>
        public static string Model_MoveBookStockItems_Source_is_missing {
            get {
                return ResourceManager.GetString("Model_MoveBookStockItems_Source_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks are identical.
        /// </summary>
        public static string Model_MoveBookStockItems_Stocks_are_identical {
            get {
                return ResourceManager.GetString("Model_MoveBookStockItems_Stocks_are_identical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to book.
        /// </summary>
        public static string Model_MoveDepositStockItems_Nothing_to_book {
            get {
                return ResourceManager.GetString("Model_MoveDepositStockItems_Nothing_to_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is missing.
        /// </summary>
        public static string Model_MoveDepositStockItems_Reason_is_missing {
            get {
                return ResourceManager.GetString("Model_MoveDepositStockItems_Reason_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock is missing.
        /// </summary>
        public static string Model_MoveDepositStockItems_Stock_is_missing {
            get {
                return ResourceManager.GetString("Model_MoveDepositStockItems_Stock_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to book.
        /// </summary>
        public static string Model_MoveRemovalStockItems_Nothing_to_book {
            get {
                return ResourceManager.GetString("Model_MoveRemovalStockItems_Nothing_to_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is missing.
        /// </summary>
        public static string Model_MoveRemovalStockItems_Reason_is_missing {
            get {
                return ResourceManager.GetString("Model_MoveRemovalStockItems_Reason_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock is missing.
        /// </summary>
        public static string Model_MoveRemovalStockItems_Stock_is_missing {
            get {
                return ResourceManager.GetString("Model_MoveRemovalStockItems_Stock_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related sales item is missing.
        /// </summary>
        public static string Model_Recipe_SalesItem_is_missing {
            get {
                return ResourceManager.GetString("Model_Recipe_SalesItem_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current production item(s).
        /// </summary>
        public static string View_AllProductionItemsView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string View_AllProductionItemsView_Header_Family {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Header_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string View_AllProductionItemsView_Header_ItemNames {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Header_ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_AllProductionItemsView_Header_Name {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.-Unit.
        /// </summary>
        public static string View_AllProductionItemsView_Header_RecipeUnit {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Header_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new production item.
        /// </summary>
        public static string View_AllProductionItemsView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a production item report.
        /// </summary>
        public static string View_AllProductionItemsView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current production item(s), if possible.
        /// </summary>
        public static string View_AllProductionItemsView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllProductionItemsView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current purchase family(s).
        /// </summary>
        public static string View_AllPurchaseFamiliesView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseFamiliesView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_AllPurchaseFamiliesView_Header_Name {
            get {
                return ResourceManager.GetString("View_AllPurchaseFamiliesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new purchase family.
        /// </summary>
        public static string View_AllPurchaseFamiliesView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseFamiliesView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a purchase families report.
        /// </summary>
        public static string View_AllPurchaseFamiliesView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseFamiliesView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current purchase family(s), if possible.
        /// </summary>
        public static string View_AllPurchaseFamiliesView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseFamiliesView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current purchase item(s).
        /// </summary>
        public static string View_AllPurchaseItemsView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string View_AllPurchaseItemsView_Header_Family {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Header_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_AllPurchaseItemsView_Header_Name {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.-Unit.
        /// </summary>
        public static string View_AllPurchaseItemsView_Header_PurchaseUnit {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Header_PurchaseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.-Unit.
        /// </summary>
        public static string View_AllPurchaseItemsView_Header_RecipeUnit {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Header_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new purchase item.
        /// </summary>
        public static string View_AllPurchaseItemsView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a purchase items report.
        /// </summary>
        public static string View_AllPurchaseItemsView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current purchase item(s), if possible.
        /// </summary>
        public static string View_AllPurchaseItemsView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllPurchaseItemsView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current recipe(s).
        /// </summary>
        public static string View_AllRecipesView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllRecipesView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string View_AllRecipesView_Header_ItemNames {
            get {
                return ResourceManager.GetString("View_AllRecipesView_Header_ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plu.
        /// </summary>
        public static string View_AllRecipesView_Header_Plu {
            get {
                return ResourceManager.GetString("View_AllRecipesView_Header_Plu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new recipe.
        /// </summary>
        public static string View_AllRecipesView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllRecipesView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a receipes report.
        /// </summary>
        public static string View_AllRecipesView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllRecipesView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current recipe(s), if possible.
        /// </summary>
        public static string View_AllRecipesView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllRecipesView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book stock items from the selected stock.
        /// </summary>
        public static string View_AllStocksView_BookFrom_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_BookFrom_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Book from.
        /// </summary>
        public static string View_AllStocksView_Button_BookFrom {
            get {
                return ResourceManager.GetString("View_AllStocksView_Button_BookFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Send to.
        /// </summary>
        public static string View_AllStocksView_Button_SendTo {
            get {
                return ResourceManager.GetString("View_AllStocksView_Button_SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit stock items in the selected stock.
        /// </summary>
        public static string View_AllStocksView_Deposit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_Deposit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current stock(s).
        /// </summary>
        public static string View_AllStocksView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string View_AllStocksView_Header_ItemNames {
            get {
                return ResourceManager.GetString("View_AllStocksView_Header_ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_AllStocksView_Header_Name {
            get {
                return ResourceManager.GetString("View_AllStocksView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new stock.
        /// </summary>
        public static string View_AllStocksView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a stocks report.
        /// </summary>
        public static string View_AllStocksView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove stock items from the selected stock.
        /// </summary>
        public static string View_AllStocksView_Removal_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_Removal_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current stock(s), if possible.
        /// </summary>
        public static string View_AllStocksView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send stock items to the selected stock.
        /// </summary>
        public static string View_AllStocksView_SendTo_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_SendTo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the content of the main bearing.
        /// </summary>
        public static string View_AllStocksView_ShowMainBearing_Tooltip {
            get {
                return ResourceManager.GetString("View_AllStocksView_ShowMainBearing_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current unit(s).
        /// </summary>
        public static string View_AllUnitsView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        public static string View_AllUnitsView_Header_Contraction {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string View_AllUnitsView_Header_FactorToParent {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_FactorToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_AllUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string View_AllUnitsView_Header_Parent {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        public static string View_AllUnitsView_Header_Purchasing {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciping.
        /// </summary>
        public static string View_AllUnitsView_Header_Reciping {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_Reciping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string View_AllUnitsView_Header_UnitType {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Header_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new unit.
        /// </summary>
        public static string View_AllUnitsView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitsView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a units report.
        /// </summary>
        public static string View_AllUnitsView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current unit(s), if possible.
        /// </summary>
        public static string View_AllUnitsView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitsView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current unit type(s).
        /// </summary>
        public static string View_AllUnitTypesView_Edit_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitTypesView_Edit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_AllUnitTypesView_Header_Name {
            get {
                return ResourceManager.GetString("View_AllUnitTypesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new unit type.
        /// </summary>
        public static string View_AllUnitTypesView_New_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitTypesView_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a unit types report.
        /// </summary>
        public static string View_AllUnitTypesView_Print_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitTypesView_Print_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current unit type(s), if possible.
        /// </summary>
        public static string View_AllUnitTypesView_Remove_Tooltip {
            get {
                return ResourceManager.GetString("View_AllUnitTypesView_Remove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database, use _integrated security:.
        /// </summary>
        public static string View_DlgSettings_DbIntegrated {
            get {
                return ResourceManager.GetString("View_DlgSettings_DbIntegrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database, _password to login:.
        /// </summary>
        public static string View_DlgSettings_DbPassword {
            get {
                return ResourceManager.GetString("View_DlgSettings_DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Database server:.
        /// </summary>
        public static string View_DlgSettings_DbServer {
            get {
                return ResourceManager.GetString("View_DlgSettings_DbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database, _user to login:.
        /// </summary>
        public static string View_DlgSettings_DbUser {
            get {
                return ResourceManager.GetString("View_DlgSettings_DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to _Matrix:.
        /// </summary>
        public static string View_DlgSettings_MatrixPath {
            get {
                return ResourceManager.GetString("View_DlgSettings_MatrixPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s settings....
        /// </summary>
        public static string View_DlgSettings_Title {
            get {
                return ResourceManager.GetString("View_DlgSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to the matrix root path.
        /// </summary>
        public static string View_DlgSettingsViewModel_BrowseMatrixPath {
            get {
                return ResourceManager.GetString("View_DlgSettingsViewModel_BrowseMatrixPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string View_MainView_Details {
            get {
                return ResourceManager.GetString("View_MainView_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string View_MainView_MainMenu_Exit {
            get {
                return ResourceManager.GetString("View_MainView_MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string View_MainView_MainMenu_File {
            get {
                return ResourceManager.GetString("View_MainView_MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string View_MainView_MainMenu_Options {
            get {
                return ResourceManager.GetString("View_MainView_MainMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string View_MainView_Menu {
            get {
                return ResourceManager.GetString("View_MainView_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Family:.
        /// </summary>
        public static string View_SingleProductionItemView_Family {
            get {
                return ResourceManager.GetString("View_SingleProductionItemView_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_SingleProductionitemView_HeaderName {
            get {
                return ResourceManager.GetString("View_SingleProductionitemView_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string View_SingleProductionitemView_HeaderQuantity {
            get {
                return ResourceManager.GetString("View_SingleProductionitemView_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string View_SingleProductionitemView_HeaderUnit {
            get {
                return ResourceManager.GetString("View_SingleProductionitemView_HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SingleProductionItemView_Id {
            get {
                return ResourceManager.GetString("View_SingleProductionItemView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string View_SingleProductionItemView_Name {
            get {
                return ResourceManager.GetString("View_SingleProductionItemView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recipe Unit:.
        /// </summary>
        public static string View_SingleProductionItemView_RecipeUnit {
            get {
                return ResourceManager.GetString("View_SingleProductionItemView_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Used items:.
        /// </summary>
        public static string View_SingleProductionItemView_UsedItems {
            get {
                return ResourceManager.GetString("View_SingleProductionItemView_UsedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SinglePurchaseFamilyView_Id {
            get {
                return ResourceManager.GetString("View_SinglePurchaseFamilyView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string View_SinglePurchaseFamilyView_Name {
            get {
                return ResourceManager.GetString("View_SinglePurchaseFamilyView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Family:.
        /// </summary>
        public static string View_SinglePurchaseItemView_Family {
            get {
                return ResourceManager.GetString("View_SinglePurchaseItemView_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SinglePurchaseItemView_Id {
            get {
                return ResourceManager.GetString("View_SinglePurchaseItemView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string View_SinglePurchaseItemView_Name {
            get {
                return ResourceManager.GetString("View_SinglePurchaseItemView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Purchase unit:.
        /// </summary>
        public static string View_SinglePurchaseItemView_PurchaseUnit {
            get {
                return ResourceManager.GetString("View_SinglePurchaseItemView_PurchaseUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recipe unit:.
        /// </summary>
        public static string View_SinglePurchaseItemView_RecipeUnit {
            get {
                return ResourceManager.GetString("View_SinglePurchaseItemView_RecipeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_SingleRecipeView_HeaderName {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string View_SingleRecipeView_HeaderQuantity {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string View_SingleRecipeView_HeaderType {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string View_SingleRecipeView_HeaderUnit {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SingleRecipeView_Id {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recipe items:.
        /// </summary>
        public static string View_SingleRecipeView_RecipeItems {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_RecipeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plu:.
        /// </summary>
        public static string View_SingleRecipeView_SalesItem {
            get {
                return ResourceManager.GetString("View_SingleRecipeView_SalesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string View_SingleStockView_HeaderArticle {
            get {
                return ResourceManager.GetString("View_SingleStockView_HeaderArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string View_SingleStockView_HeaderQuantity {
            get {
                return ResourceManager.GetString("View_SingleStockView_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string View_SingleStockView_HeaderType {
            get {
                return ResourceManager.GetString("View_SingleStockView_HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string View_SingleStockView_HeaderUnit {
            get {
                return ResourceManager.GetString("View_SingleStockView_HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SingleStockView_Id {
            get {
                return ResourceManager.GetString("View_SingleStockView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string View_SingleStockView_Name {
            get {
                return ResourceManager.GetString("View_SingleStockView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Items in stock:.
        /// </summary>
        public static string View_SingleStockView_StockItems {
            get {
                return ResourceManager.GetString("View_SingleStockView_StockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SingleUnitTypeView_Id {
            get {
                return ResourceManager.GetString("View_SingleUnitTypeView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string View_SingleUnitTypeView_Name {
            get {
                return ResourceManager.GetString("View_SingleUnitTypeView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Contraction:.
        /// </summary>
        public static string View_SingleUnitView_Contraction {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Factor:.
        /// </summary>
        public static string View_SingleUnitView_Factor {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string View_SingleUnitView_Id {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string View_SingleUnitView_Name {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_arent:.
        /// </summary>
        public static string View_SingleUnitView_Parent {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for _purchasing.
        /// </summary>
        public static string View_SingleUnitView_Purchasing {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for _reciping.
        /// </summary>
        public static string View_SingleUnitView_Reciping {
            get {
                return ResourceManager.GetString("View_SingleUnitView_Reciping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit _type:.
        /// </summary>
        public static string View_SingleUnitView_UnitType {
            get {
                return ResourceManager.GetString("View_SingleUnitView_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move from stock:.
        /// </summary>
        public static string View_StockItemBookingView_FromStock {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_FromStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        public static string View_StockItemBookingView_HeaderInStock {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_HeaderInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string View_StockItemBookingView_HeaderItem {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_HeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string View_StockItemBookingView_HeaderQuantity {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string View_StockItemBookingView_HeaderUnit {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to move:.
        /// </summary>
        public static string View_StockItemBookingView_StockItems {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_StockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move into stock:.
        /// </summary>
        public static string View_StockItemBookingView_ToStock {
            get {
                return ResourceManager.GetString("View_StockItemBookingView_ToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        public static string View_StockItemDepositView_HeaderInStock {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_HeaderInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string View_StockItemDepositView_HeaderItem {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_HeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string View_StockItemDepositView_HeaderQuantity {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string View_StockItemDepositView_HeaderUnit {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string View_StockItemDepositView_Reason {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit to stock:.
        /// </summary>
        public static string View_StockItemDepositView_Stock {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to deposit:.
        /// </summary>
        public static string View_StockItemDepositView_StockItems {
            get {
                return ResourceManager.GetString("View_StockItemDepositView_StockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        public static string View_StockItemRemovalView_HeaderInStock {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_HeaderInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string View_StockItemRemovalView_HeaderItem {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_HeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string View_StockItemRemovalView_HeaderQuantity {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_HeaderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string View_StockItemRemovalView_HeaderUnit {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_HeaderUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string View_StockItemRemovalView_Reason {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal from stock:.
        /// </summary>
        public static string View_StockItemRemovalView_Stock {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to remove:.
        /// </summary>
        public static string View_StockItemRemovalView_StockItems {
            get {
                return ResourceManager.GetString("View_StockItemRemovalView_StockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following production item(s):.
        /// </summary>
        public static string ViewModel_AllProductionIetmsViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllProductionIetmsViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove production item(s).
        /// </summary>
        public static string ViewModel_AllProductionItemsViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllProductionItemsViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Production items.
        /// </summary>
        public static string ViewModel_AllProductionItemsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllProductionItemsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of production items].
        /// </summary>
        public static string ViewModel_AllProductionItemsViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllProductionItemsViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following purchase family(ies):.
        /// </summary>
        public static string ViewModel_AllPurchaseFamiliesViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseFamiliesViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove purchase family(ies).
        /// </summary>
        public static string ViewModel_AllPurchaseFamiliesViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseFamiliesViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Purchase families.
        /// </summary>
        public static string ViewModel_AllPurchaseFamiliesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseFamiliesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of purchase families].
        /// </summary>
        public static string ViewModel_AllPurchaseFamiliesViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseFamiliesViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following purchase item(s):.
        /// </summary>
        public static string ViewModel_AllPurchaseItemsViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseItemsViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove purchase item(s).
        /// </summary>
        public static string ViewModel_AllPurchaseItemsViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseItemsViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Purchase items.
        /// </summary>
        public static string ViewModel_AllPurchaseItemsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseItemsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of purchase items].
        /// </summary>
        public static string ViewModel_AllPurchaseItemsViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllPurchaseItemsViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following recipe(s):.
        /// </summary>
        public static string ViewModel_AllRecipesViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllRecipesViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove recipe(s).
        /// </summary>
        public static string ViewModel_AllRecipesViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllRecipesViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All recipes.
        /// </summary>
        public static string ViewModel_AllRecipesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllRecipesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of recipes].
        /// </summary>
        public static string ViewModel_AllRecipesViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllRecipesViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following stock(s):.
        /// </summary>
        public static string ViewModel_AllStocksViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllStocksViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove stock(s).
        /// </summary>
        public static string ViewModel_AllStocksViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllStocksViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All stocks.
        /// </summary>
        public static string ViewModel_AllStocksViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllStocksViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of stocks].
        /// </summary>
        public static string ViewModel_AllStocksViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllStocksViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following unit(s):.
        /// </summary>
        public static string ViewModel_AllUnitsViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitsViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unit(s).
        /// </summary>
        public static string ViewModel_AllUnitsViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitsViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All units.
        /// </summary>
        public static string ViewModel_AllUnitsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of units].
        /// </summary>
        public static string ViewModel_AllUnitsViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitsViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the following unit type(s):.
        /// </summary>
        public static string ViewModel_AllUnitTypesViewModel_AskToDelete {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitTypesViewModel_AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unit type(s).
        /// </summary>
        public static string ViewModel_AllUnitTypesViewModel_DeleteItems {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitTypesViewModel_DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unit types.
        /// </summary>
        public static string ViewModel_AllUnitTypesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitTypesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [List of unit types].
        /// </summary>
        public static string ViewModel_AllUnitTypesViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_AllUnitTypesViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new production item.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewProductionItem {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewProductionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new purchase family.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewPurchaseFamily {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewPurchaseFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new purchase item.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewPurchaseItem {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewPurchaseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new recipe.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewRecipe {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new stock.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewStock {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new unit.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewUnit {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new unit type.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_CreateNewUnitType {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_CreateNewUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Control System.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View production items.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllProductionItems {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllProductionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View purchase families.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllPurchaseFamilies {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllPurchaseFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View purchase items.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllPurchaseItems {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllPurchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recipes.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllRecipes {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View stocks.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllStocks {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View units.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllUnits {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View unit types.
        /// </summary>
        public static string ViewModel_MainWindowViewModel_ViewAllUnitTypes {
            get {
                return ResourceManager.GetString("ViewModel_MainWindowViewModel_ViewAllUnitTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SingleProductionItemViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SingleProductionItemViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New production item.
        /// </summary>
        public static string ViewModel_SingleProductionItemViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SingleProductionItemViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SinglePurchaseFamilyViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SinglePurchaseFamilyViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New purchase family.
        /// </summary>
        public static string ViewModel_SinglePurchaseFamilyViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SinglePurchaseFamilyViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SinglePurchaseItemViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SinglePurchaseItemViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New purchase item.
        /// </summary>
        public static string ViewModel_SinglePurchaseItemViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SinglePurchaseItemViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe for {0}.
        /// </summary>
        public static string ViewModel_SingleRecipeViewModel_EditItem {
            get {
                return ResourceManager.GetString("ViewModel_SingleRecipeViewModel_EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SingleRecipeViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SingleRecipeViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New recipe.
        /// </summary>
        public static string ViewModel_SingleRecipeViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SingleRecipeViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SingleStockViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SingleStockViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New stock.
        /// </summary>
        public static string ViewModel_SingleStockViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SingleStockViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Stock {0}].
        /// </summary>
        public static string ViewModel_SingleStockViewModel_PrintHeader {
            get {
                return ResourceManager.GetString("ViewModel_SingleStockViewModel_PrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SingleUnitTypeViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SingleUnitTypeViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New unit type.
        /// </summary>
        public static string ViewModel_SingleUnitTypeViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SingleUnitTypeViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New).
        /// </summary>
        public static string ViewModel_SingleUnitViewModel_NewId {
            get {
                return ResourceManager.GetString("ViewModel_SingleUnitViewModel_NewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New unit.
        /// </summary>
        public static string ViewModel_SingleUnitViewModel_NewItem {
            get {
                return ResourceManager.GetString("ViewModel_SingleUnitViewModel_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main bearing.
        /// </summary>
        public static string ViewModel_StockItemBookinViewModel_MainInventory {
            get {
                return ResourceManager.GetString("ViewModel_StockItemBookinViewModel_MainInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock item booking.
        /// </summary>
        public static string ViewModel_StockItemBookinViewModel_Title {
            get {
                return ResourceManager.GetString("ViewModel_StockItemBookinViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit in stock.
        /// </summary>
        public static string ViewModel_StockItemDepositViewModel_Title {
            get {
                return ResourceManager.GetString("ViewModel_StockItemDepositViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal from stock.
        /// </summary>
        public static string ViewModel_StockItemRemovalViewModel_Title {
            get {
                return ResourceManager.GetString("ViewModel_StockItemRemovalViewModel_Title", resourceCulture);
            }
        }
    }
}
