//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucifer.Pms.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucifer.Pms.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current currency.
        /// </summary>
        public static string AllCurrenciesView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllCurrenciesView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        public static string AllCurrenciesView_Header_Contraction {
            get {
                return ResourceManager.GetString("AllCurrenciesView_Header_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllCurrenciesView_Header_Name {
            get {
                return ResourceManager.GetString("AllCurrenciesView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string AllCurrenciesView_Header_Symbol {
            get {
                return ResourceManager.GetString("AllCurrenciesView_Header_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new currency.
        /// </summary>
        public static string AllCurrenciesView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllCurrenciesView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current currency.
        /// </summary>
        public static string AllCurrenciesView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllCurrenciesView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following currencies:
        ///.
        /// </summary>
        public static string AllCurrenciesView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllCurrenciesView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove currencies.
        /// </summary>
        public static string AllCurrenciesView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllCurrenciesView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current payform.
        /// </summary>
        public static string AllPayformsView_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AllPayformsView_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllPayformsView_Header_Name {
            get {
                return ResourceManager.GetString("AllPayformsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new payform.
        /// </summary>
        public static string AllPayformsView_New_ToolTip {
            get {
                return ResourceManager.GetString("AllPayformsView_New_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current payform.
        /// </summary>
        public static string AllPayformsView_Remove_ToolTip {
            get {
                return ResourceManager.GetString("AllPayformsView_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the following payforms:
        ///.
        /// </summary>
        public static string AllPayformsView_RemoveMessage {
            get {
                return ResourceManager.GetString("AllPayformsView_RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove payforms.
        /// </summary>
        public static string AllPayformsView_RemoveTitle {
            get {
                return ResourceManager.GetString("AllPayformsView_RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string CurrenciesModule {
            get {
                return ResourceManager.GetString("CurrenciesModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage currency informations and rates.
        /// </summary>
        public static string CurrenciesTooltip {
            get {
                return ResourceManager.GetString("CurrenciesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of currency is missing.
        /// </summary>
        public static string CurrencyModel_Name_missing {
            get {
                return ResourceManager.GetString("CurrencyModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of currency is missing.
        /// </summary>
        public static string CurrencyModel_Symbol_missing {
            get {
                return ResourceManager.GetString("CurrencyModel_Symbol_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Contraction:.
        /// </summary>
        public static string EditCurrencyView_Contraction {
            get {
                return ResourceManager.GetString("EditCurrencyView_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency {0}.
        /// </summary>
        public static string EditCurrencyView_CurrencyIs {
            get {
                return ResourceManager.GetString("EditCurrencyView_CurrencyIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditCurrencyView_Name {
            get {
                return ResourceManager.GetString("EditCurrencyView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New currency&gt;.
        /// </summary>
        public static string EditCurrencyView_NewCurrency {
            get {
                return ResourceManager.GetString("EditCurrencyView_NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Symbol:.
        /// </summary>
        public static string EditCurrencyView_Symbol {
            get {
                return ResourceManager.GetString("EditCurrencyView_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit currency.
        /// </summary>
        public static string EditCurrencyView_TitleEdit {
            get {
                return ResourceManager.GetString("EditCurrencyView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new currency....
        /// </summary>
        public static string EditCurrencyView_TitleNew {
            get {
                return ResourceManager.GetString("EditCurrencyView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditPayformView_Name {
            get {
                return ResourceManager.GetString("EditPayformView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;New Payform&gt;.
        /// </summary>
        public static string EditPayformView_NewPayform {
            get {
                return ResourceManager.GetString("EditPayformView_NewPayform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payform {0}.
        /// </summary>
        public static string EditPayformView_PayformIs {
            get {
                return ResourceManager.GetString("EditPayformView_PayformIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit payform.
        /// </summary>
        public static string EditPayformView_TitleEdit {
            get {
                return ResourceManager.GetString("EditPayformView_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new payform....
        /// </summary>
        public static string EditPayformView_TitleNew {
            get {
                return ResourceManager.GetString("EditPayformView_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of payform is missing.
        /// </summary>
        public static string PayformModel_Name_missing {
            get {
                return ResourceManager.GetString("PayformModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payforms.
        /// </summary>
        public static string PayformsModule {
            get {
                return ResourceManager.GetString("PayformsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage payforms and their relation to external modules.
        /// </summary>
        public static string PayformsTooltip {
            get {
                return ResourceManager.GetString("PayformsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Management.
        /// </summary>
        public static string PmsModuleTitle {
            get {
                return ResourceManager.GetString("PmsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to control your POS envrionment.
        /// </summary>
        public static string PmsModuleTooltip {
            get {
                return ResourceManager.GetString("PmsModuleTooltip", resourceCulture);
            }
        }
    }
}
