//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetpro.WPF.TableReport.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dotnetpro.WPF.TableReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string btAbbrechen {
            get {
                return ResourceManager.GetString("btAbbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string btClose {
            get {
                return ResourceManager.GetString("btClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenschaften ähnelt.
        /// </summary>
        public static string btDruckerEinstellung {
            get {
                return ResourceManager.GetString("btDruckerEinstellung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seitenbreite ähnelt.
        /// </summary>
        public static string btOptBreite {
            get {
                return ResourceManager.GetString("btOptBreite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ganze Seite ähnelt.
        /// </summary>
        public static string btOptHoehe {
            get {
                return ResourceManager.GetString("btOptHoehe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite einrichten ähnelt.
        /// </summary>
        public static string btSeitenEinstellung {
            get {
                return ResourceManager.GetString("btSeitenEinstellung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starten ähnelt.
        /// </summary>
        public static string btStartDefault {
            get {
                return ResourceManager.GetString("btStartDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Drucken ähnelt.
        /// </summary>
        public static string btStartPrint {
            get {
                return ResourceManager.GetString("btStartPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hochformat ähnelt.
        /// </summary>
        public static string cbAnsichtHoch {
            get {
                return ResourceManager.GetString("cbAnsichtHoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Querformat ähnelt.
        /// </summary>
        public static string cbAnsichtQuer {
            get {
                return ResourceManager.GetString("cbAnsichtQuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopien ähnelt.
        /// </summary>
        public static string cbCopiesPlural {
            get {
                return ResourceManager.GetString("cbCopiesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopie ähnelt.
        /// </summary>
        public static string cbCopiesSingular {
            get {
                return ResourceManager.GetString("cbCopiesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite ähnelt.
        /// </summary>
        public static string cbSeite {
            get {
                return ResourceManager.GetString("cbSeite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die feste Spaltenbreite ähnelt.
        /// </summary>
        public static string chkFixedColumnWidth {
            get {
                return ResourceManager.GetString("chkFixedColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mit Spaltenlinien ähnelt.
        /// </summary>
        public static string chkSpaltenlinien {
            get {
                return ResourceManager.GetString("chkSpaltenlinien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelliereffekt ähnelt.
        /// </summary>
        public static string chkTabelliereffekt {
            get {
                return ResourceManager.GetString("chkTabelliereffekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mit Zeilenlinien ähnelt.
        /// </summary>
        public static string chkZeilenlinien {
            get {
                return ResourceManager.GetString("chkZeilenlinien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seiten ähnelt.
        /// </summary>
        public static string grpSeiten {
            get {
                return ResourceManager.GetString("grpSeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau ähnelt.
        /// </summary>
        public static string grpVorschau {
            get {
                return ResourceManager.GetString("grpVorschau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Exemplare ähnelt.
        /// </summary>
        public static string lbAnzahl {
            get {
                return ResourceManager.GetString("lbAnzahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drucker ähnelt.
        /// </summary>
        public static string lbDrucker {
            get {
                return ResourceManager.GetString("lbDrucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftgröße ähnelt.
        /// </summary>
        public static string lbFont {
            get {
                return ResourceManager.GetString("lbFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        /// </summary>
        public static string lbFormat {
            get {
                return ResourceManager.GetString("lbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bis Seite ähnelt.
        /// </summary>
        public static string lbSeitenBis {
            get {
                return ResourceManager.GetString("lbSeitenBis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die von Seite ähnelt.
        /// </summary>
        public static string lbSeitenVon {
            get {
                return ResourceManager.GetString("lbSeitenVon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erzeuge Seite $1 von $2 ähnelt.
        /// </summary>
        public static string prgSeiten {
            get {
                return ResourceManager.GetString("prgSeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles drucken ähnelt.
        /// </summary>
        public static string radioAlleSeiten {
            get {
                return ResourceManager.GetString("radioAlleSeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seiten ähnelt.
        /// </summary>
        public static string radioSeitenAuswahl {
            get {
                return ResourceManager.GetString("radioSeitenAuswahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Druck: $1, Benutzer &apos;$2&apos; ähnelt.
        /// </summary>
        public static string sInfo {
            get {
                return ResourceManager.GetString("sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite $1 von $2 ähnelt.
        /// </summary>
        public static string sSeite {
            get {
                return ResourceManager.GetString("sSeite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anfang ähnelt.
        /// </summary>
        public static string ttFirst {
            get {
                return ResourceManager.GetString("ttFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        /// </summary>
        public static string ttLast {
            get {
                return ResourceManager.GetString("ttLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vorwärts ähnelt.
        /// </summary>
        public static string ttNext {
            get {
                return ResourceManager.GetString("ttNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rückwärts ähnelt.
        /// </summary>
        public static string ttPrevious {
            get {
                return ResourceManager.GetString("ttPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau ähnelt.
        /// </summary>
        public static string WTitelDefault {
            get {
                return ResourceManager.GetString("WTitelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Druckvorschau ähnelt.
        /// </summary>
        public static string WTitelDruck {
            get {
                return ResourceManager.GetString("WTitelDruck", resourceCulture);
            }
        }
    }
}
