//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nubis.Funding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nubis.Funding.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string FundingData_LabelDarlehensBetrag {
            get {
                return ResourceManager.GetString("FundingData_LabelDarlehensBetrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective rate:.
        /// </summary>
        public static string FundingData_LabelEffektivZins {
            get {
                return ResourceManager.GetString("FundingData_LabelEffektivZins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed rate time:.
        /// </summary>
        public static string FundingData_LabelFestZinsDauer {
            get {
                return ResourceManager.GetString("FundingData_LabelFestZinsDauer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        public static string FundingData_LabelLaufzeit {
            get {
                return ResourceManager.GetString("FundingData_LabelLaufzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly fund:.
        /// </summary>
        public static string FundingData_LabelMonatsRate {
            get {
                return ResourceManager.GetString("FundingData_LabelMonatsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal rate:.
        /// </summary>
        public static string FundingData_LabelNominalZins {
            get {
                return ResourceManager.GetString("FundingData_LabelNominalZins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (YY.MM).
        /// </summary>
        public static string FundingData_LabelYearMonthHint {
            get {
                return ResourceManager.GetString("FundingData_LabelYearMonthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        public static string FundingData_LabelZahlungsweise {
            get {
                return ResourceManager.GetString("FundingData_LabelZahlungsweise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding data.
        /// </summary>
        public static string FundingDataViewModel_DisplayName {
            get {
                return ResourceManager.GetString("FundingDataViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data to calculate financement.
        /// </summary>
        public static string FundingDataViewModel_ToolTip {
            get {
                return ResourceManager.GetString("FundingDataViewModel_ToolTip", resourceCulture);
            }
        }
    }
}
